sudo: required
services:
    - docker

before_install:
    - docker build -t eppy25/react-test -f ./client/src/Dockerfile.dev ./client

script:
    - docker run -e CI=true eppy25/react-test npm test

after_success:
    - docker build -t eppy25/multi-client ./client
    - docker build -t eppy25/multi-nginx ./nginx
    - docker build -t eppy25/multi-server ./server
    - docker build -t eppy25/multi-worker ./worker

# Log in to the Docker CLI
    - echo "$DOCK_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

# Take those images and push them to Docker Hub
    - docker push eppy25/multi-client
    - docker push eppy25/multi-nginx
    - docker push eppy25/multi-server
    - docker push eppy25/multi-worker
